### ISSUE TITLE
Error while trying to compile Godot

### ISSUE THREAD

**Issue by moonarts** [Malkverbena/mysql#21]
- I cloned Godot from the master branch
- I cloned the MySQL module
- I downloaded and installed both Boost library and MySQL C++ Connector
- I modified the SCsub file for the paths of the Boost library and MySQL C++ Connector
- I put the MySQL module into the modules folder of the godot folder

But I'm getting an error while trying to compile Godot with SCons on Windows :
https://pastebin.com/FEWrez9T

**Comment by Malkverbena** [comment]
What error you got?

**Comment by moonarts** [comment]
modules\mysql\mysql.cpp(282): error C2131: l'expression n'a pas été évaluée en constante
modules\mysql\mysql.cpp(282): note: L'échec est dû à la lecture d'une variable obsolète
modules\mysql\mysql.cpp(282): note: voir l'utilisation de 'length'
modules\mysql\mysql.cpp(283): error C2668: 'std::basic_istream<char,std::char_traits<char>>::get' : appel ambigu à une fonction surchargée
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\istream(404): note: est peut-être 'std::basic_istream<char,std::char_traits<char>> &std::basic_istream<char,std::char_traits<char>>::get(std::basic_streambuf<char,std::char_traits<char>> &,_Elem)'
        with
        [
            _Elem=char
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\istream(358): note: ou       'std::basic_istream<char,std::char_traits<char>> &std::basic_istream<char,std::char_traits<char>>::get(_Elem *,std::streamsize)'
        with
        [
            _Elem=char
        ]
modules\mysql\mysql.cpp(283): note: lors de la tentative de mise en correspondance de la liste des arguments '(char [length], int)'
modules\mysql\mysql.cpp(299): error C2131: l'expression n'a pas été évaluée en constante
modules\mysql\mysql.cpp(299): note: L'échec est dû à la lecture d'une variable obsolète
modules\mysql\mysql.cpp(299): note: voir l'utilisation de 'length'
modules\mysql\mysql.cpp(300): error C2668: 'std::basic_istream<char,std::char_traits<char>>::get' : appel ambigu à une fonction surchargée
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\istream(404): note: est peut-être 'std::basic_istream<char,std::char_traits<char>> &std::basic_istream<char,std::char_traits<char>>::get(std::basic_streambuf<char,std::char_traits<char>> &,_Elem)'
        with
        [
            _Elem=char
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\istream(358): note: ou       'std::basic_istream<char,std::char_traits<char>> &std::basic_istream<char,std::char_traits<char>>::get(_Elem *,std::streamsize)'
        with
        [
            _Elem=char
        ]
modules\mysql\mysql.cpp(300): note: lors de la tentative de mise en correspondance de la liste des arguments '(char [length], int)'
modules\mysql\mysql.cpp(509): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'or'
modules\mysql\mysql.cpp(509): error C2065: 'or' : identificateur non déclaré
modules\mysql\mysql.cpp(509): error C2146: erreur de syntaxe : absence de ';' avant l'identificateur 'p_option'
modules\mysql\mysql.cpp(509): error C2059: erreur de syntaxe : ')'
modules\mysql\mysql.cpp(510): error C2062: type 'int' inattendu
modules\mysql\mysql.cpp(511): error C2065: 'p_ret' : identificateur non déclaré
modules\mysql\mysql.cpp(512): error C2065: 'p_ret' : identificateur non déclaré
modules\mysql\mysql.cpp(495): error C2317: bloc 'try' commençant ligne '495' n'a pas de gestionnaires catch
modules\mysql\mysql.cpp(514): error C2181: instruction else sans if correspondant non conforme
modules\mysql\mysql.cpp(516): error C2065: 'option' : identificateur non déclaré
modules\mysql\mysql.cpp(525): error C2059: erreur de syntaxe : 'catch'
modules\mysql\mysql.cpp(525): error C2143: erreur de syntaxe : absence de ';' avant '{'
modules\mysql\mysql.cpp(525): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
modules\mysql\mysql.cpp(528): error C2059: erreur de syntaxe : 'catch'
modules\mysql\mysql.cpp(528): error C2143: erreur de syntaxe : absence de ';' avant '{'
modules\mysql\mysql.cpp(528): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
modules\mysql\mysql.cpp(531): error C2059: erreur de syntaxe : 'return'
modules\mysql\mysql.cpp(532): error C2059: erreur de syntaxe : '}'
modules\mysql\mysql.cpp(532): error C2143: erreur de syntaxe : absence de ';' avant '}'
modules\mysql\mysql.cpp(535): error C2143: erreur de syntaxe : absence de ';' avant '{'
modules\mysql\mysql.cpp(535): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
xr_generated_dispatch_table.c
modules\mysql\mysql.cpp(710): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'or'
modules\mysql\mysql.cpp(710): error C2065: 'or' : identificateur non déclaré
modules\mysql\mysql.cpp(710): error C2146: erreur de syntaxe : absence de ';' avant l'identificateur 'prop_type'
modules\mysql\mysql.cpp(710): error C2059: erreur de syntaxe : ')'
modules\mysql\mysql.cpp(712): error C2275: 'String' : utilisation non conforme de ce type comme expression
.\core/os/thread.h(47): note: voir la déclaration de 'String'
modules\mysql\mysql.cpp(712): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur '_ret'
modules\mysql\mysql.cpp(713): error C2065: '_ret' : identificateur non déclaré
modules\mysql\mysql.cpp(715): error C2059: erreur de syntaxe : 'else'
modules\mysql\mysql.cpp(715): error C2653: 'PROPERTY_TYPES' : n'est pas un nom de classe ni d'espace de noms
modules\mysql\mysql.cpp(715): error C2143: erreur de syntaxe : absence de ';' avant '{'
modules\mysql\mysql.cpp(715): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
modules\mysql\mysql.cpp(720): error C2059: erreur de syntaxe : 'else'
modules\mysql\mysql.cpp(720): error C2653: 'PROPERTY_TYPES' : n'est pas un nom de classe ni d'espace de noms
modules\mysql\mysql.cpp(720): error C2143: erreur de syntaxe : absence de ';' avant '{'
modules\mysql\mysql.cpp(720): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
modules\mysql\mysql.cpp(725): error C2059: erreur de syntaxe : 'else'
modules\mysql\mysql.cpp(725): error C2653: 'PROPERTY_TYPES' : n'est pas un nom de classe ni d'espace de noms
modules\mysql\mysql.cpp(725): error C2143: erreur de syntaxe : absence de ';' avant '{'
modules\mysql\mysql.cpp(725): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
modules\mysql\mysql.cpp(736): error C2059: erreur de syntaxe : 'else'
modules\mysql\mysql.cpp(736): error C2653: 'PROPERTY_TYPES' : n'est pas un nom de classe ni d'espace de noms
modules\mysql\mysql.cpp(736): error C2143: erreur de syntaxe : absence de ';' avant '{'
modules\mysql\mysql.cpp(736): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
modules\mysql\mysql.cpp(745): error C2059: erreur de syntaxe : 'return'
modules\mysql\mysql.cpp(746): error C2059: erreur de syntaxe : '}'
modules\mysql\mysql.cpp(746): error C2143: erreur de syntaxe : absence de ';' avant '}'
modules\mysql\mysql.cpp(751): error C2143: erreur de syntaxe : absence de ';' avant '{'
modules\mysql\mysql.cpp(751): error C2447: '{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)
[Initial build] Compiling modules\ogg\register_types.cpp ...
modules\mysql\mysql.cpp(876): warning C4996: 'strtok': This function or variable may be unsafe. Consider using strtok_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
modules\mysql\mysql.cpp(885): warning C4996: 'strtok': This function or variable may be unsafe. Consider using strtok_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
[Initial build] Compiling modules\ogg\ogg_packet_sequence.cpp ...
[Initial build] Compiling modules\navigation\godot_navigation_server.cpp ...
[Initial build] Compiling modules\navigation\rvo_agent.cpp ...
register_types.cpp
[Initial build] Compiling modules\navigation\navigation_mesh_generator.cpp ...
ogg_packet_sequence.cpp
scons: *** [modules\mysql\mysql.windows.editor.x86_64.obj] Error 2
godot_navigation_server.cpp
rvo_agent.cpp
navigation_mesh_generator.cpp
scons: building terminated because of errors.
[Time elapsed: 00:06:17.447]

**Comment by Malkverbena** [comment]
It looks like your Boost library is not installed correctly.

**Comment by Malkverbena** [comment]
Are you able to compile it?

**Comment by moonarts** [comment]
No I didn't succeed. I switched on PostgreSQL with another library, thanks.
