### ISSUE TITLE
Unable to compile SSL when turned on

### ISSUE THREAD

**Issue by majenkotech** [Malkverbena/mysql#26]
This looks like a pathing error, as it's trying to find SSL within boost....

    FileNotFoundError: [Errno 2] No such file or directory: '/home/matt/godot/modules/mysql/3party/boost/3party/openssl':

**Comment by Malkverbena** [comment]
Related with [#25](https://github.com/Malkverbena/mysql/issues/25)

**Comment by Malkverbena** [comment]
Can you give more details?
