### ISSUE TITLE
No match for operator =

### ISSUE THREAD

**Issue by majenkotech** [Malkverbena/mysql#28]
```
modules/mysql/scr/mysql.cpp:403:121: error: no match for 'operator=' (operand types are 'std::tuple<boost::system::error_code&, boost::mysql::statement&>' and 'std::tuple<boost::system::error_code>')
```

Caused by this line:

```
std::tie(ec, prep_stmt) = co_await unix_ssl_conn->async_close_statement(prep_stmt, diag, tuple_awaitable);
```

within `MySQL::coro_execute_prepared()`.

This is probably related to the fix from #27

**Comment by Malkverbena** [comment]
@majenkotech I apreciate a lot your feedback.
Sometimes small things flee from my eyes.

**Comment by majenkotech** [comment]
It's always good to have a separate tester with a different system. I've been a software developer on and off for the past 35 years and well understand the challenges of solo or small team programming and testing on multiple environments.
